name: Test Tag

on:
  workflow_dispatch:
    inputs:
            tagToTest:
              description: 'Tag to test'
              required: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.inputs.tagToTest }}
      - name: Test Tag
        run: |
          pip install . 
